name: phrases
description: phrases in English then Spanish

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: ^0.15.1
  animated_text_kit: ^2.2.0
  assets_audio_player: ^2.0.1+3
  audioplayer: ^0.8.1
  just_audio: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/
    - assets/audios/
